# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: bantucerdas-api
  RUN_REGION: asia-southeast2
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  DOCKER_PKG_REGION: ${{ secrets.GCP_DOCKER_PKG_REGION }}
  DOCKER_REPO: ${{ secrets.GCP_DOCKER_REPO }}
  DOCKER_IMAGE: ${{ secrets.GCP_DOCKER_IMAGE }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag asia-southeast2-docker.pkg.dev/bantucerdas-aa6ec/bantucerdas-repo/bantucerdas-api-image:latest:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image asia-southeast2-docker.pkg.dev/bantucerdas-aa6ec/bantucerdas-repo/bantucerdas-api-image:latest:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
